tweet/tweet/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('', include("tweetapp.urls")),
    path('admin/', admin.site.urls),
    path("", include("django.contrib.auth.urls")),
]

tweet/tweetapp/urls.py
from django.urls import path
from .  import views

app_name = "tweetapp"

urlpatterns = [
    path('', views.listtweet,name="listtweet"),
    path('addtweet/', views.addtweet,name="addtweet"),
    path("signup/",views.SignUpView.as_view(),name="signup"),
    path("deletetweet/<int:id>",views.deletetweet , name="deletetweet")
]

tweet/tweetapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Tweet(models.Model) :
    username = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    message = models.CharField(max_length=100)
    
    def __str__(self):
         return f"Tweet User : {self.username} message : {self.message}"

tweet/tweetapp/views.py
from django.shortcuts import render,redirect
from . import models
from django.urls import reverse ,reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView

def listtweet(request):
    all_tweets = models.Tweet.objects.all()
    tweet_dict = {"tweets": all_tweets}   
    return render(request, "tweetapp/listtweet.html", context=tweet_dict)
@login_required(login_url="/login")
def addtweet(request):
    if request.method == "POST":
        message = request.POST.get("message", "")
        models.Tweet.objects.create(username=request.user,message = message)
        return redirect(reverse("tweetapp:listtweet")) 
    else : 
        
       return render(request, "tweetapp/addtweet.html")
@login_required
def deletetweet(requst,id) :
    tweet = models.Tweet.objects.get(pk=id)
    if requst.user == tweet.username :
        models.Tweet.objects.filter(id=id).delete()
        return redirect("tweetapp:listtweet")
    
       
   
class SignUpView(CreateView) :
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

tweet/templates/base.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Tweet App</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>
  <body>
   

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'tweetapp:listtweet' %}">Tweet App</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarCollapse"
          aria-controls="navbarCollapse"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'tweetapp:listtweet' %}">List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tweetapp:addtweet' %}">Add Tweet</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tweetapp:signup' %}">Signup</a>
            </li>
          </ul>
          <li class="nav-item">
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="next" value="/">
                <button type="submit" class="nav-link" style="border: none; background: none; cursor: pointer;">Logout</button>
            </form>
        </li>
        </ul>
      
        
        </div>
      </div>
    </nav>
    {% block content %}
    {% endblock content %} 
  </body>
</html>

tweet/tweetapp/templates/tweetapp/addtweet.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h1>Add Tweet Page</h1>

    <form action="" method="post">
        {% csrf_token %} 
        
        <div class="mb-3 row">
            <label for="message" class="col-sm-2 col-form-label">Message</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="message" name="message" placeholder="What's on your mind?">
            </div>
        </div>

        <div class="text-center">
            <button type="submit" class="btn btn-primary">Send Tweet</button>
        </div>
    </form>
</div>
{% endblock content %}

tweet/tweetapp/templates/tweetapp/listtweet.html
{% extends "base.html" %}

{%block content%}
<div class="container" style="width: 50%;">
    {%for tweet in tweets%}
    <div class="card" style="padding: 5px;">
        <div class="card-header" style="background-color: cornflowerblue;">
           <h4> {{tweet.username}}</h4>
        </div>
        <div class="card-body">
            <p class="card-text">{{tweet.message}}</p>
        </div>
        {%if tweet.username == user%}
        <a href="{% url 'tweetapp:deletetweet' id=tweet.id %}" class="btn btn-danger">Delete</a>
        {%endif%}
    </div>
    {%endfor%}
</div>
{%endblock%}